# Generated by Django 2.1.2 on 2018-10-25 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20181025_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 25, 23, 22, 4, 433493)),
        ),
    ]
